name: codecov

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codecov:
    timeout-minutes: 15

    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: go version && go mod download

      - name: Run tests with coverage
        run: make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./.testCoverage
