name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    timeout-minutes: 15

    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.19", "1.20", "1.21" ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install linters
        run: make install-linters

      - name: Get dependencies
        run: go version && go mod download

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint
